# https://github.com/koalaman/shellcheck/wiki/TravisCI
sudo: required
language: bash
services:
  - docker
before_install:
  - docker pull koalaman/shellcheck
script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck eless
matrix:
  fast_finish: true
